identifier_name:
    allowed_symbols: ["_"]
    validates_start_with_lowercase: false
    min_length:
        warning: 1
line_length:
  warning: 140
  error: 300
  ignores_comments: true
  ignores_urls: true

excluded: 
  - Pods
